/// <reference lib="webworker" />
import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching'
import { registerRoute } from 'workbox-routing'
import { NetworkFirst, StaleWhileRevalidate, CacheFirst } from 'workbox-strategies'
import { BackgroundSyncPlugin } from 'workbox-background-sync'
import { ExpirationPlugin } from 'workbox-expiration'

declare let self: ServiceWorkerGlobalScope

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST)
cleanupOutdatedCaches()

// Background Sync for Supabase API calls (Journal logs, Reports, etc.)
const bgSyncPlugin = new BackgroundSyncPlugin('supabase-queue', {
  maxRetentionTime: 24 * 60, // Retry for max 24 Hours (in minutes)
})

// Cache Supabase API calls with Background Sync for mutations
registerRoute(
  ({ url }) => url.href.includes('supabase.co'),
  new NetworkFirst({
    cacheName: 'supabase-api',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 7 * 24 * 60 * 60, // 1 week
      }),
      bgSyncPlugin,
    ],
  }),
  'POST'
)

registerRoute(
  ({ url }) => url.href.includes('supabase.co'),
  new NetworkFirst({
    cacheName: 'supabase-api',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 7 * 24 * 60 * 60, // 1 week
      }),
      bgSyncPlugin,
    ],
  }),
  'PATCH'
)

// Standard data fetching: Stale-While-Revalidate for reads
registerRoute(
  ({ url }) => url.href.includes('supabase.co'),
  new StaleWhileRevalidate({
    cacheName: 'supabase-data',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 200,
        maxAgeSeconds: 24 * 60 * 60, // 24 hours
      }),
    ],
  }),
  'GET'
)

// Cache fonts and static assets
registerRoute(
  ({ request }) => request.destination === 'font',
  new CacheFirst({
    cacheName: 'assets-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 20,
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 Days
      }),
    ],
  })
)

// Handle SPA routing
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting()
  }
})
